include(InstallRequiredSystemLibraries)

# Контактная информация (обязательна для DEB и RPM)
set(CPACK_PACKAGE_CONTACT " <>")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "")

set(CPACK_PACKAGE_VERSION_MAJOR 0)
set(CPACK_PACKAGE_VERSION_MINOR 1)
set(CPACK_PACKAGE_VERSION_PATCH 0)
set(CPACK_PACKAGE_VERSION_TWEAK 0)
set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}.${CPACK_PACKAGE_VERSION_TWEAK}")
set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Quadratic equation solver application with banking system")

set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

# Компоненты для упаковки
set(CPACK_COMPONENTS_ALL applications libraries)
set(CPACK_COMPONENT_APPLICATIONS_DISPLAY_NAME "Solver Application")
set(CPACK_COMPONENT_LIBRARIES_DISPLAY_NAME "Solver and Formatter Libraries")

# RPM package
set(CPACK_RPM_PACKAGE_NAME "solver-app")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "Development/Tools")
set(CPACK_RPM_CHANGELOG_FILE ${CMAKE_CURRENT_SOURCE_DIR}/ChangeLog.md)
set(CPACK_RPM_PACKAGE_RELEASE 1)

# DEB package
set(CPACK_DEBIAN_PACKAGE_NAME "solver-app")
set(CPACK_DEBIAN_PACKAGE_PREDEPENDS "cmake >= 3.14")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

include(CPack)
