include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_CONTACT "${GITHUB_USERNAME} <${GITHUB_EMAIL}>")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_CONTACT}")

set(CPACK_PACKAGE_VERSION_MAJOR 0)
set(CPACK_PACKAGE_VERSION_MINOR 1)
set(CPACK_PACKAGE_VERSION_PATCH 0)
set(CPACK_PACKAGE_VERSION_TWEAK 0)
set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}.${CPACK_PACKAGE_VERSION_TWEAK}")
set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Quadratic equation solver application with banking system")

set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

# Компоненты для установки
set(CPACK_COMPONENTS_ALL applications)

# RPM package
set(CPACK_RPM_PACKAGE_NAME "solver-app")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "Development/Tools")
set(CPACK_RPM_CHANGELOG_FILE ${CMAKE_CURRENT_SOURCE_DIR}/ChangeLog.md)
set(CPACK_RPM_PACKAGE_RELEASE 1)

# DEB package
set(CPACK_DEBIAN_PACKAGE_NAME "solver-app")
set(CPACK_DEBIAN_PACKAGE_PREDEPENDS "cmake >= 3.14")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

# macOS DragNDrop settings
set(CPACK_DMG_VOLUME_NAME "Solver App ${CPACK_PACKAGE_VERSION}")
set(CPACK_DMG_FORMAT "UDBZ")

# Windows WIX settings - без лицензии
set(CPACK_WIX_PRODUCT_NAME "Solver Application")
set(CPACK_WIX_MANUFACTURER "${GITHUB_USERNAME}")
set(CPACK_WIX_INSTALL_SCOPE "perMachine")
set(CPACK_WIX_UPGRADE_GUID "2A185A5D-0B90-44EC-8642-9DDB1B581CF4")
# Отключаем файл лицензии
set(CPACK_WIX_LICENSE_RTF "")

include(CPack)
